### ISSUE TITLE
Deadliest Warrior + DLC

### ISSUE THREAD

**Issue by NovaAetas** [AnimMouse/psn-pkg-torrents#6]
Hey

I've been searching forever for the Deadliest Warrior DLC's (PS3).

Would you be able to add?

**Comment by AnimMouse** [comment]
I have added Deadliest Warrior - The Game PS3 and Deadliest Warrior Legends PS3 @ bb7984df652933b09da27962786e0b67b0ba1d17
For DLC, what I can find is the Deadliest Warrior: The Game™ Fan Favorite Warriors Expansion Pack available at [NoPayStation](https://nopaystation.com/view/PS3/NPUB30309/0000000PACKAGE00/0?version=1), no need to torrent it as the DLC size is just 2.4 MiB.
